# 通用配置
spring:
  application:
    name: Yachiyo
    yaml:
  profiles:
    include: secret
  ai:
    ollama:
      chat:
        options:
          model: tsukimi-yachiyo
      embedding:
        enabled: true
        model: all-minilm
      base-url: http://localhost:11434


baidu:
  translate:
    api-key: ${baidu.translate.api-key}
    secret-key: ${baidu.translate.secret-key}
    app-id: ${baidu.translate.app-id}
