# 通用配置
spring:
  application:
    name: Yachiyo
    yaml:
  profiles:
    include: secret
  ai:
    ollama:
      chat:
        options:
          model: 1473443474/tsukimi-yachiyo
      embedding:
        enabled: true
        model: all-minilm
      base-url: http://localhost:11434


