# 通用配置
spring:
  application:
    name: Yachiyo
  ai:
    ollama:
      chat:
        options:
          model: tsukimi-yachiyo
      embedding:
        enabled: true
        model: all-minilm
      base-url: http://localhost:11434